export const colorPalette = {
  border: "oklch(1 0 0 / 0.1)",
  primary: "oklch(0.922 0 0)",
  secondary: "oklch(0.269 0 0)",
  accent: "oklch(0.627 0.265 303.9)",
  muted: "oklch(0.269 0 0)",
  card: "oklch(0.205 0 0)",
  background: "oklch(0.145 0 0)",
  chart1: "oklch(0.488 0.243 264.376)",
  chart2: "oklch(0.696 0.17 162.48)",
  chart3: "oklch(0.769 0.188 70.08)",
  chart4: "oklch(0.627 0.265 303.9)",
  chart5: "oklch(0.645 0.246 16.439)",
  ring: "oklch(0.556 0 0)",
};

export const editorThemeColors = {
  bg: colorPalette.background,
  card: colorPalette.card,
  border: colorPalette.secondary,
};

export const codeSnippetsData = [
  {
    text: "const app = express();",
    language: "JavaScript",
    color: colorPalette.chart3,
  },
  { text: "def fibonacci(n):", language: "Python", color: colorPalette.chart2 },
  {
    text: '<div className="app">',
    language: "JSX",
    color: colorPalette.chart4,
  },
  { text: "display: flex;", language: "CSS", color: colorPalette.chart1 },
  {
    text: 'import React from "react";',
    language: "JavaScript",
    color: colorPalette.chart3,
  },
  {
    text: "async function fetchData()",
    language: "TypeScript",
    color: colorPalette.chart1,
  },
  { text: "SELECT * FROM users;", language: "SQL", color: colorPalette.chart2 },
  {
    text: "interface Props {",
    language: "TypeScript",
    color: colorPalette.chart4,
  },
  {
    text: ".map((item) => ...)",
    language: "JavaScript",
    color: colorPalette.chart3,
  },
  { text: "pip install numpy", language: "CLI", color: colorPalette.chart2 },
  {
    text: 'git commit -m "feat:"',
    language: "CLI",
    color: colorPalette.chart5,
  },
  {
    text: "export default App;",
    language: "JavaScript",
    color: colorPalette.chart3,
  },
  { text: "color: #00ff88;", language: "CSS", color: colorPalette.chart1 },
  {
    text: "const [state, setState]",
    language: "React",
    color: colorPalette.chart4,
  },
  {
    text: 'print("Hello World")',
    language: "Python",
    color: colorPalette.chart2,
  },
  { text: "npm run build", language: "CLI", color: colorPalette.chart5 },
  { text: "return <Layout />", language: "JSX", color: colorPalette.chart4 },
  {
    text: "background: linear-gradient",
    language: "CSS",
    color: colorPalette.chart1,
  },
  { text: "useEffect(() => {", language: "React", color: colorPalette.chart4 },
  {
    text: "for (let i = 0; i < n; i++)",
    language: "JavaScript",
    color: colorPalette.chart3,
  },
  {
    text: "class Node<T> {",
    language: "TypeScript",
    color: colorPalette.chart1,
  },
  { text: "border-radius: 8px;", language: "CSS", color: colorPalette.chart1 },
  {
    text: "app.listen(3000);",
    language: "JavaScript",
    color: colorPalette.chart3,
  },
  {
    text: "raise ValueError()",
    language: "Python",
    color: colorPalette.chart2,
  },
];

export const typingSnippets = [
  {
    language: "JavaScript",
    file: "api.js",
    icon: "JS",
    iconBg: "#c8a016",
    iconFg: "#0d0d0f",
    accentColor: "#c8a016",
    lines: [
      [
        { c: "#c792ea", v: "const " },
        { c: "#82aaff", v: "fetchUsers" },
        { c: "#89ddff", v: " = " },
        { c: "#c792ea", v: "async" },
        { c: "#89ddff", v: " () => {" },
      ],
      [
        { c: "#89ddff", v: "  " },
        { c: "#c792ea", v: "const " },
        { c: "#eeffff", v: "res" },
        { c: "#89ddff", v: " = " },
        { c: "#c792ea", v: "await " },
        { c: "#82aaff", v: "fetch" },
        { c: "#89ddff", v: "(" },
        { c: "#c3e88d", v: '"/api/users"' },
        { c: "#89ddff", v: ");" },
      ],
      [
        { c: "#89ddff", v: "  " },
        { c: "#c792ea", v: "if " },
        { c: "#89ddff", v: "(!res." },
        { c: "#82aaff", v: "ok" },
        { c: "#89ddff", v: ") " },
        { c: "#c792ea", v: "throw new " },
        { c: "#ffcb6b", v: "Error" },
        { c: "#89ddff", v: "(res." },
        { c: "#82aaff", v: "status" },
        { c: "#89ddff", v: ");" },
      ],
      [
        { c: "#89ddff", v: "  " },
        { c: "#c792ea", v: "const " },
        { c: "#eeffff", v: "data" },
        { c: "#89ddff", v: " = " },
        { c: "#c792ea", v: "await " },
        { c: "#eeffff", v: "res" },
        { c: "#89ddff", v: "." },
        { c: "#82aaff", v: "json" },
        { c: "#89ddff", v: "();" },
      ],
      [
        { c: "#89ddff", v: "  " },
        { c: "#c792ea", v: "return " },
        { c: "#eeffff", v: "data" },
        { c: "#89ddff", v: "." },
        { c: "#82aaff", v: "map" },
        { c: "#89ddff", v: "(" },
        { c: "#ffcb6b", v: "u" },
        { c: "#89ddff", v: " => " },
        { c: "#eeffff", v: "u" },
        { c: "#89ddff", v: "." },
        { c: "#82aaff", v: "name" },
        { c: "#89ddff", v: ");" },
      ],
      [{ c: "#89ddff", v: "};" }],
    ],
  },
  {
    language: "Python",
    file: "train.py",
    icon: "PY",
    iconBg: "#3b8ad9",
    iconFg: "#ffffff",
    accentColor: "#3b8ad9",
    lines: [
      [
        { c: "#c792ea", v: "import " },
        { c: "#82aaff", v: "torch" },
        { c: "#89ddff", v: "; " },
        { c: "#c792ea", v: "import " },
        { c: "#82aaff", v: "torch.nn" },
        { c: "#89ddff", v: " as " },
        { c: "#eeffff", v: "nn" },
      ],
      [{ c: "#89ddff", v: "" }],
      [
        { c: "#c792ea", v: "class " },
        { c: "#ffcb6b", v: "MLP" },
        { c: "#89ddff", v: "(" },
        { c: "#82aaff", v: "nn.Module" },
        { c: "#89ddff", v: "):" },
      ],
      [
        { c: "#89ddff", v: "  " },
        { c: "#c792ea", v: "def " },
        { c: "#82aaff", v: "__init__" },
        { c: "#89ddff", v: "(" },
        { c: "#ffcb6b", v: "self" },
        { c: "#89ddff", v: ", " },
        { c: "#ffcb6b", v: "dims" },
        { c: "#89ddff", v: "):" },
      ],
      [
        { c: "#89ddff", v: "    " },
        { c: "#c792ea", v: "super" },
        { c: "#89ddff", v: "()." },
        { c: "#82aaff", v: "__init__" },
        { c: "#89ddff", v: "()" },
      ],
      [
        { c: "#89ddff", v: "    " },
        { c: "#eeffff", v: "self" },
        { c: "#89ddff", v: "." },
        { c: "#82aaff", v: "net" },
        { c: "#89ddff", v: " = " },
        { c: "#82aaff", v: "nn.Sequential" },
        { c: "#89ddff", v: "(*[" },
      ],
      [
        { c: "#89ddff", v: "      " },
        { c: "#82aaff", v: "nn.Linear" },
        { c: "#89ddff", v: "(" },
        { c: "#eeffff", v: "dims" },
        { c: "#89ddff", v: "[i], " },
        { c: "#eeffff", v: "dims" },
        { c: "#89ddff", v: "[i+1])" },
      ],
    ],
  },
  {
    language: "TypeScript",
    file: "types.ts",
    icon: "TS",
    iconBg: "#007acc",
    iconFg: "#ffffff",
    accentColor: "#007acc",
    lines: [
      [
        { c: "#c792ea", v: "interface " },
        { c: "#ffcb6b", v: "ApiResponse" },
        { c: "#89ddff", v: "<" },
        { c: "#ffcb6b", v: "T" },
        { c: "#89ddff", v: "> {" },
      ],
      [
        { c: "#89ddff", v: "  " },
        { c: "#82aaff", v: "data" },
        { c: "#89ddff", v: ": " },
        { c: "#ffcb6b", v: "T" },
      ],
      [
        { c: "#89ddff", v: "  " },
        { c: "#82aaff", v: "status" },
        { c: "#89ddff", v: ": " },
        { c: "#c3e88d", v: "'ok'" },
        { c: "#89ddff", v: " | " },
        { c: "#c3e88d", v: "'error'" },
      ],
      [
        { c: "#89ddff", v: "  " },
        { c: "#82aaff", v: "meta" },
        { c: "#89ddff", v: ": {" },
      ],
      [
        { c: "#89ddff", v: "    " },
        { c: "#82aaff", v: "timestamp" },
        { c: "#89ddff", v: ": " },
        { c: "#ffcb6b", v: "number" },
      ],
      [
        { c: "#89ddff", v: "    " },
        { c: "#82aaff", v: "requestId" },
        { c: "#89ddff", v: ": " },
        { c: "#ffcb6b", v: "string" },
      ],
      [{ c: "#89ddff", v: "  }" }],
      [{ c: "#89ddff", v: "}" }],
    ],
  },
  {
    language: "CSS",
    file: "layout.css",
    icon: "CSS",
    iconBg: "#264de4",
    iconFg: "#ffffff",
    accentColor: "#264de4",
    lines: [
      [
        { c: "#82aaff", v: ".hero" },
        { c: "#89ddff", v: " {" },
      ],
      [
        { c: "#89ddff", v: "  " },
        { c: "#c3e88d", v: "display" },
        { c: "#89ddff", v: ": " },
        { c: "#f78c6c", v: "grid" },
      ],
      [
        { c: "#89ddff", v: "  " },
        { c: "#c3e88d", v: "grid-template-columns" },
        { c: "#89ddff", v: ": " },
        { c: "#f78c6c", v: "repeat(3, 1fr)" },
      ],
      [
        { c: "#89ddff", v: "  " },
        { c: "#c3e88d", v: "backdrop-filter" },
        { c: "#89ddff", v: ": " },
        { c: "#f78c6c", v: "blur(20px)" },
      ],
      [
        { c: "#89ddff", v: "  " },
        { c: "#c3e88d", v: "border" },
        { c: "#89ddff", v: ": " },
        { c: "#f78c6c", v: "1px solid rgba(255,255,255,.1)" },
      ],
      [
        { c: "#89ddff", v: "  " },
        { c: "#c3e88d", v: "border-radius" },
        { c: "#89ddff", v: ": " },
        { c: "#f78c6c", v: "12px" },
      ],
      [{ c: "#89ddff", v: "}" }],
    ],
  },
  {
    language: "React",
    file: "Theme.tsx",
    icon: "TSX",
    iconBg: "#007acc",
    iconFg: "#ffffff",
    accentColor: "#61dafb",
    lines: [
      [
        { c: "#c792ea", v: "const " },
        { c: "#82aaff", v: "ThemeProvider" },
        { c: "#89ddff", v: " = (" },
        { c: "#ffcb6b", v: "{ children }" },
        { c: "#89ddff", v: ") => {" },
      ],
      [
        { c: "#89ddff", v: "  " },
        { c: "#c792ea", v: "const " },
        { c: "#89ddff", v: "[" },
        { c: "#eeffff", v: "theme" },
        { c: "#89ddff", v: ", " },
        { c: "#eeffff", v: "setTheme" },
        { c: "#89ddff", v: "] = " },
        { c: "#82aaff", v: "useState" },
        { c: "#89ddff", v: "(" },
        { c: "#c3e88d", v: '"dark"' },
        { c: "#89ddff", v: ");" },
      ],
      [
        { c: "#89ddff", v: "  " },
        { c: "#82aaff", v: "useEffect" },
        { c: "#89ddff", v: "(() => {" },
      ],
      [
        { c: "#89ddff", v: "    " },
        { c: "#eeffff", v: "document" },
        { c: "#89ddff", v: "." },
        { c: "#82aaff", v: "body" },
        { c: "#89ddff", v: "." },
        { c: "#82aaff", v: "className" },
        { c: "#89ddff", v: " = " },
        { c: "#eeffff", v: "theme" },
        { c: "#89ddff", v: ";" },
      ],
      [
        { c: "#89ddff", v: "  }, [" },
        { c: "#eeffff", v: "theme" },
        { c: "#89ddff", v: "]);" },
      ],
      [
        { c: "#89ddff", v: "  " },
        { c: "#c792ea", v: "return " },
        { c: "#89ddff", v: "<" },
        { c: "#82aaff", v: "ctx.Provider" },
        { c: "#89ddff", v: " value={{ theme, setTheme }}>" },
      ],
      [{ c: "#89ddff", v: "    {children}" }],
    ],
  },
];
